# Generated by Django 4.2 on 2023-07-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('Buah-buahan', 'Buah-buahan'), ('Sayur-sayuran', 'Sayur-sayuran'), ('Daging-Ayam-Ikan', 'Daging dan Ayam'), ('Bumbu-Dapur', 'Bumbu Dapur')], max_length=20),
        ),
    ]
