# Generated by Django 4.2 on 2023-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('Buah-buahan', 'Buah-buahan'), ('Sayur-sayuran', 'Sayur-sayuran'), ('Daging-Ayam', 'Daging dan Ayam'), ('Bumbu-Dapur', 'Bumbu Dapur')], max_length=20),
        ),
    ]
