# Generated by Django 4.2 on 2023-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0016_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
