# Generated by Django 4.2 on 2023-07-06 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0022_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkitem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='produkitem',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
